spring:
  application:
    name: demo
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql:replication://127.0.0.1:3306,127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=false&useSSL=false&failOverReadOnly=true&loadBalanceStrategy=random&readFormMasterNoSlaves=true
    driver-class-name: com.mysql.jdbc.ReplicationDriver
    username: root
    password: root
  redis:
    database: 0
    host: 10.110.1.254
    password:
    port: 6379
    ssl: false

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  ssl:
    enabled: false
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
  port: 2019
